/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Basti
 */
public class Carrito extends javax.swing.JFrame {

    /**
     * Creates new form Carrito
     */
    public Carrito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFieldTotal = new javax.swing.JTextField();
        textFieldnom2 = new javax.swing.JTextField();
        textFieldprecio2 = new javax.swing.JTextField();
        textFieldnom3 = new javax.swing.JTextField();
        textFieldprecio3 = new javax.swing.JTextField();
        textFieldnom4 = new javax.swing.JTextField();
        textFieldprecio4 = new javax.swing.JTextField();
        textFieldnom5 = new javax.swing.JTextField();
        textFieldnom6 = new javax.swing.JTextField();
        textFieldprecio5 = new javax.swing.JTextField();
        textFieldprecio6 = new javax.swing.JTextField();
        textFieldnom7 = new javax.swing.JTextField();
        textFieldprecio7 = new javax.swing.JTextField();
        textFieldnom1 = new javax.swing.JTextField();
        textFieldprecio1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bPagar = new javax.swing.JButton();
        bRegresar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        inicioMenu = new javax.swing.JMenu();
        produMenu = new javax.swing.JMenu();
        juegoMenu = new javax.swing.JMenu();
        ofertMenu = new javax.swing.JMenu();
        contactMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("hooge 05_53", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Carrito");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 110, 30));

        jLabel1.setFont(new java.awt.Font("hooge 05_53", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Productos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, -1));

        jLabel4.setFont(new java.awt.Font("hooge 05_53", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Precio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 90, -1));

        jLabel5.setFont(new java.awt.Font("hooge 05_53", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Nombre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, -1));
        getContentPane().add(textFieldTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 140, -1));
        getContentPane().add(textFieldnom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 140, -1));

        textFieldprecio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldprecio2ActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldprecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 140, -1));
        getContentPane().add(textFieldnom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, -1));
        getContentPane().add(textFieldprecio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 140, -1));

        textFieldnom4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldnom4ActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldnom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 140, -1));
        getContentPane().add(textFieldprecio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 140, -1));
        getContentPane().add(textFieldnom5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 140, -1));
        getContentPane().add(textFieldnom6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 140, -1));
        getContentPane().add(textFieldprecio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 140, -1));
        getContentPane().add(textFieldprecio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 140, -1));
        getContentPane().add(textFieldnom7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 140, -1));
        getContentPane().add(textFieldprecio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 140, -1));
        getContentPane().add(textFieldnom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 140, -1));
        getContentPane().add(textFieldprecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 140, -1));

        jLabel3.setFont(new java.awt.Font("hooge 05_53", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Total");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 70, -1));

        bPagar.setText("Pagar");
        getContentPane().add(bPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 80, -1));

        bRegresar.setText("Regresar");
        getContentPane().add(bRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Basti\\OneDrive\\Documentos\\NetBeansProjects\\JBEM\\src\\main\\java\\Imagenes\\fondo931x831.png")); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 650, 570));

        inicioMenu.setText("Inicio");
        inicioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(inicioMenu);

        produMenu.setText("Productos");
        jMenuBar1.add(produMenu);

        juegoMenu.setText("Juego");
        jMenuBar1.add(juegoMenu);

        ofertMenu.setText("Ofertas");
        jMenuBar1.add(ofertMenu);

        contactMenu.setText("Contacto");
        jMenuBar1.add(contactMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldprecio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldprecio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldprecio2ActionPerformed

    private void textFieldnom4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldnom4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldnom4ActionPerformed

    private void inicioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioMenuActionPerformed

    }//GEN-LAST:event_inicioMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carrito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPagar;
    private javax.swing.JButton bRegresar;
    private javax.swing.JMenu contactMenu;
    private javax.swing.JLabel fondo;
    private javax.swing.JMenu inicioMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu juegoMenu;
    private javax.swing.JMenu ofertMenu;
    private javax.swing.JMenu produMenu;
    private javax.swing.JTextField textFieldTotal;
    private javax.swing.JTextField textFieldnom1;
    private javax.swing.JTextField textFieldnom2;
    private javax.swing.JTextField textFieldnom3;
    private javax.swing.JTextField textFieldnom4;
    private javax.swing.JTextField textFieldnom5;
    private javax.swing.JTextField textFieldnom6;
    private javax.swing.JTextField textFieldnom7;
    private javax.swing.JTextField textFieldprecio1;
    private javax.swing.JTextField textFieldprecio2;
    private javax.swing.JTextField textFieldprecio3;
    private javax.swing.JTextField textFieldprecio4;
    private javax.swing.JTextField textFieldprecio5;
    private javax.swing.JTextField textFieldprecio6;
    private javax.swing.JTextField textFieldprecio7;
    // End of variables declaration//GEN-END:variables
}
