package Vista;

import Model.DAO.PCDAO;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Hardware extends javax.swing.JFrame {

    public Hardware() throws SQLException {
        initComponents();
        cargarComponentesP();
        cargarComponentesTG();
        cargarComponentesR();
        cargarComponentesFP();
        cargarComponentesPM();
        cargarComponentesV();
        cargarComponentesAlma();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboProce = new javax.swing.JComboBox<>();
        comboGrafi = new javax.swing.JComboBox<>();
        comboRam = new javax.swing.JComboBox<>();
        comboFuente = new javax.swing.JComboBox<>();
        comboVentila = new javax.swing.JComboBox<>();
        comboAlmace = new javax.swing.JComboBox<>();
        comboPlaca = new javax.swing.JComboBox<>();
        labProce = new javax.swing.JLabel();
        labTarj = new javax.swing.JLabel();
        labRam = new javax.swing.JLabel();
        labFuente = new javax.swing.JLabel();
        labVenti = new javax.swing.JLabel();
        labAlma = new javax.swing.JLabel();
        labjuego7 = new javax.swing.JLabel();
        iconoJBEM = new javax.swing.JLabel();
        botonCarrito = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        inicioMenu = new javax.swing.JMenu();
        produMenu = new javax.swing.JMenu();
        juegoMenu = new javax.swing.JMenu();
        ofertMenu = new javax.swing.JMenu();
        contactMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(940, 880));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboProce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboProce, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 630, -1));

        comboGrafi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboGrafi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 630, -1));

        comboRam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 630, -1));

        comboFuente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 630, -1));

        comboVentila.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboVentila, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 630, -1));

        comboAlmace.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboAlmace, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 680, 630, -1));

        comboPlaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(comboPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 630, -1));

        labProce.setFont(new java.awt.Font("hooge 05_55", 0, 14)); // NOI18N
        labProce.setForeground(new java.awt.Color(204, 204, 255));
        labProce.setText("Procesador");
        getContentPane().add(labProce, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 150, 30));

        labTarj.setFont(new java.awt.Font("hooge 05_55", 0, 14)); // NOI18N
        labTarj.setForeground(new java.awt.Color(204, 204, 255));
        labTarj.setText("Tarjeta grafica");
        getContentPane().add(labTarj, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 150, 30));

        labRam.setFont(new java.awt.Font("hooge 05_55", 0, 14)); // NOI18N
        labRam.setForeground(new java.awt.Color(204, 204, 255));
        labRam.setText("Ram");
        getContentPane().add(labRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 150, 30));

        labFuente.setFont(new java.awt.Font("hooge 05_55", 0, 14)); // NOI18N
        labFuente.setForeground(new java.awt.Color(204, 204, 255));
        labFuente.setText("Fuente de poder");
        getContentPane().add(labFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 150, 30));

        labVenti.setFont(new java.awt.Font("hooge 05_55", 0, 14)); // NOI18N
        labVenti.setForeground(new java.awt.Color(204, 204, 255));
        labVenti.setText("Ventilación");
        getContentPane().add(labVenti, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 150, 30));

        labAlma.setFont(new java.awt.Font("hooge 05_55", 0, 14)); // NOI18N
        labAlma.setForeground(new java.awt.Color(204, 204, 255));
        labAlma.setText("Almacenamiento");
        getContentPane().add(labAlma, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 650, 150, 30));

        labjuego7.setFont(new java.awt.Font("hooge 05_55", 0, 14)); // NOI18N
        labjuego7.setForeground(new java.awt.Color(204, 204, 255));
        labjuego7.setText("Placa madre");
        getContentPane().add(labjuego7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 150, 30));

        iconoJBEM.setIcon(new javax.swing.ImageIcon("C:\\Users\\Basti\\OneDrive\\Documentos\\NetBeansProjects\\JBEM\\src\\main\\java\\Imagenes\\JBEM.png")); // NOI18N
        iconoJBEM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        getContentPane().add(iconoJBEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 150, 150));

        botonCarrito.setText("Ver carrito");
        botonCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarritoActionPerformed(evt);
            }
        });
        getContentPane().add(botonCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 760, 160, 40));

        botonRegresar.setText("Regresar");
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 760, 160, 40));

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Basti\\OneDrive\\Documentos\\NetBeansProjects\\JBEM\\src\\main\\java\\Imagenes\\fondo.png")); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 880));

        inicioMenu.setText("Inicio");
        inicioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(inicioMenu);

        produMenu.setText("Productos");
        jMenuBar1.add(produMenu);

        juegoMenu.setText("Juego");
        jMenuBar1.add(juegoMenu);

        ofertMenu.setText("Ofertas");
        jMenuBar1.add(ofertMenu);

        contactMenu.setText("Contacto");
        jMenuBar1.add(contactMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPlacaActionPerformed

    private void inicioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioMenuActionPerformed

    }//GEN-LAST:event_inicioMenuActionPerformed

    private void botonCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCarritoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Hardware().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Hardware.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCarrito;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JComboBox<String> comboAlmace;
    private javax.swing.JComboBox<String> comboFuente;
    private javax.swing.JComboBox<String> comboGrafi;
    private javax.swing.JComboBox<String> comboPlaca;
    public javax.swing.JComboBox<String> comboProce;
    private javax.swing.JComboBox<String> comboRam;
    private javax.swing.JComboBox<String> comboVentila;
    private javax.swing.JMenu contactMenu;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel iconoJBEM;
    private javax.swing.JMenu inicioMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu juegoMenu;
    private javax.swing.JLabel labAlma;
    private javax.swing.JLabel labFuente;
    private javax.swing.JLabel labProce;
    private javax.swing.JLabel labRam;
    private javax.swing.JLabel labTarj;
    private javax.swing.JLabel labVenti;
    private javax.swing.JLabel labjuego7;
    private javax.swing.JMenu ofertMenu;
    private javax.swing.JMenu produMenu;
    // End of variables declaration//GEN-END:variables

    private void cargarComponentesP() throws SQLException {
        PCDAO procesadorDAO = new PCDAO();
        List<String> procesadores = procesadorDAO.obtenerProcesadores();

        comboProce.removeAllItems();
        for (String procesador : procesadores) {
            comboProce.addItem(procesador);
        }

    }

    private void cargarComponentesTG() throws SQLException {
        PCDAO tarjetagraficaDAO = new PCDAO();
        List<String> graficas = tarjetagraficaDAO.obtenerGraficas();

        comboGrafi.removeAllItems();
        for (String graf : graficas) {
            comboGrafi.addItem(graf);
        }

    }

    private void cargarComponentesR() throws SQLException {
        PCDAO ramdao = new PCDAO();
        List<String> rams = ramdao.obtenerRAM();

        comboRam.removeAllItems();
        for (String ra : rams) {
            comboRam.addItem(ra);
        }

    }

    private void cargarComponentesFP() throws SQLException {
        PCDAO fpdao = new PCDAO();
        List<String> fp = fpdao.obtenerFP();

        comboFuente.removeAllItems();
        for (String fpoder : fp) {
            comboFuente.addItem(fpoder);
        }

    }

    private void cargarComponentesPM() throws SQLException {
        PCDAO pmdao = new PCDAO();
        List<String> pm = pmdao.obtenerPM();

        comboPlaca.removeAllItems();
        for (String pMadre : pm) {
            comboPlaca.addItem(pMadre);
        }

    }

    private void cargarComponentesV() throws SQLException {
        PCDAO VenDAO = new PCDAO();
        List<String> ven = VenDAO.obtenerVent();

        comboVentila.removeAllItems();
        for (String venti : ven) {
            comboVentila.addItem(venti);
        }

    }

    private void cargarComponentesAlma() throws SQLException {
        PCDAO almaDAO = new PCDAO();
        List<String> almac = almaDAO.obtenerAlma();

        comboAlmace.removeAllItems();
        for (String alm : almac) {
            comboAlmace.addItem(alm);
        }

    }
}
